Repository Spring-Rookies/Head-First-Java-Book-3th-Edition, pull requests merged in 2022-09, with the labels that each got.

#1 :books: [DOCS]: JDK releases e Doc inicial
  chapter_01/adivinhar.md
  chapter_01/imagens/jdk-releases.png
  chapter_01/imagens/jvm.jpg
Labels: documentation, enhancement

#2 :construction:[FEAT] Criada três classes testes
  chapter_01/classes/IfTest.java
  chapter_01/classes/MyFirstApp.java
  chapter_01/classes/WhileTest.java
  chapter_01/imagens/java-flow.png
Labels: documentation, enhancement

#4 :wrench:[FIX] Corrigido o padrão do diretório raiz
  chapter_01/outros/adivinhar.md
Labels: bug

#5 :pencil:[DOCS] Licença MIT
  LICENSE
Labels: documentation

#6 :pencil::[EXERCISES] Adição de três exercícios
  chapter_01/exercicios/calculeIdade.java
  chapter_01/exercicios/calculeMedia.java
  chapter_01/exercicios/diasParaACopaDoMundo.java
Labels: enhancement

#8 :recycle:: [FIX] Corrigido os nomes das classes.
  chapter_01/exercicios/calculeIdade.java
  chapter_01/exercicios/calculeMedia.java
  chapter_01/exercicios/diasParaACopaDoMundo.java
Labels: enhancement

#9 :pencil:: [EXERCISES] Adicao do exercicio tabuada.
  chapter_01/exercicios/Tabuada.java
Labels: enhancement

#10 ✨ [FEAT] Adição de dois exercícios
  chapter_01/classes/IfTest.java
  chapter_01/classes/MyFirstApp.java
  chapter_01/classes/PhraseOMatic.java
  chapter_01/classes/Shuffle1.java
  chapter_01/classes/WhileTest.java
Labels: enhancement

#12 :recycle::[REFACTOR] Pasta chapter_01 refatorada
  chapter_01/classes/Shuffle1.java
  chapter_01/exercicios/CalcularIdade.java
  chapter_01/exercicios/CalcularMedia.java
  chapter_01/exercicios/CronometroCopaDoMundo.java
  chapter_01/exercicios/IfTest.java
  chapter_01/exercicios/MyFirstApp.java
  chapter_01/exercicios/PhraseOMatic.java
  chapter_01/exercicios/Tabuada.java
  chapter_01/exercicios/WhileTest.java
Labels: enhancement
